from_latest_tag = false
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    "bun x set-version {{version}}",
    "echo 'Upgraded Root Package to {{version}}'",
    "git add package.json",
]
post_bump_hooks = []
pre_package_bump_hooks = [
    "bun x set-version {{version}}",
    "echo 'Upgraded {{package}} to {{version}}'",
    "git add package.json",
]
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages."@autorelease-test/package-a"]
path = "./package-a"
include = ["package-a/**"]
public_api = true

[packages."@autorelease-test/package-b"]
path = "./package-b"
include = ["package-b/**"]
public_api = true

[packages."@autorelease-test/package-c"]
path = "./package-c"
include = ["package-c/**"]
public_api = false
